# Generated by Django 5.0.3 on 2024-03-11 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcmTokens', models.CharField()),
                ('uid', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='maka.user')),
                ('phone', models.CharField()),
                ('email', models.CharField()),
                ('recieve_promotions', models.CharField()),
                ('zip_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ConversationStarters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maka.user')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesting', models.CharField()),
                ('birthday', models.DateField()),
                ('nickName', models.CharField()),
                ('occupation', models.CharField()),
                ('orientation', models.CharField()),
                ('relationship_status', models.CharField()),
                ('active', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maka.user')),
            ],
        ),
    ]
