# Generated by Django 5.0.3 on 2024-03-14 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maka', '0004_rename_event_end_event_event_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField()),
                ('guest_type', models.TextField()),
                ('is_host', models.BooleanField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maka.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maka.user')),
            ],
        ),
    ]
