# Generated by Django 5.0.3 on 2024-03-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maka', '0006_remove_user_id_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fcmTokens',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
