# Generated by Django 5.0.3 on 2024-03-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maka', '0007_alter_user_fcmtokens_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
