# Generated by Django 5.0.3 on 2024-03-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maka', '0008_alter_profile_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
