# Generated by Django 5.0.3 on 2024-03-14 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maka', '0011_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(null=True)),
                ('email', models.CharField(null=True)),
                ('recieve_promotions', models.CharField()),
                ('zip_code', models.IntegerField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maka.user')),
            ],
        ),
        migrations.DeleteModel(
            name='GuestContact',
        ),
    ]
