# Generated by Django 5.0.3 on 2024-03-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maka', '0012_guestcontacts_delete_guestcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestcontacts',
            name='recieve_promotions',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='guestcontacts',
            name='zip_code',
            field=models.IntegerField(null=True),
        ),
    ]
