# Generated by Django 5.0.3 on 2024-03-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maka', '0013_alter_guestcontacts_recieve_promotions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestcontacts',
            name='recieve_promotions',
        ),
        migrations.AddField(
            model_name='user',
            name='recieve_promotions',
            field=models.CharField(null=True),
        ),
    ]
