# Generated by Django 5.0.3 on 2024-03-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maka', '0014_remove_guestcontacts_recieve_promotions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestcontacts',
            name='facebook',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='guestcontacts',
            name='instagram',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='guestcontacts',
            name='linkedin',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='guestcontacts',
            name='snapchat',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='guestcontacts',
            name='tiktok',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='guestcontacts',
            name='x',
            field=models.CharField(null=True),
        ),
    ]
