# Generated by Django 5.0.3 on 2024-03-15 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maka', '0017_eventtype_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcheckin',
            name='check_in_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventcheckin',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maka.user'),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maka.user'),
        ),
    ]
