# Generated by Django 5.0.3 on 2024-03-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maka', '0018_alter_eventcheckin_check_in_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.TextField(default='MakaEvent'),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name='PointOfContact',
            new_name='KeyPerson',
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.TextField()),
                ('key_persons', models.ManyToManyField(to='maka.keyperson')),
            ],
        ),
    ]
