# Generated by Django 5.0.3 on 2024-03-16 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maka', '0019_event_name_rename_pointofcontact_keyperson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaboration_status', models.TextField()),
                ('collaborating_orgs', models.ManyToManyField(to='maka.organization')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maka.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_feedback', models.TextField()),
                ('user_ratings', models.TextField()),
                ('comments', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maka.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketing_materials', models.TextField()),
                ('social_media_links', models.TextField()),
                ('promotional_offers', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maka.event')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_history', models.TextField()),
                ('events_viewed', models.TextField()),
                ('tickets_purchased', models.TextField()),
                ('likes_given', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maka.user')),
            ],
        ),
    ]
