# Generated by Django 5.0.3 on 2024-03-16 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maka', '0020_eventcollaboration_eventfeedback_eventpromotion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maka.event'),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='interaction_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
