# Generated by Django 5.0.3 on 2024-03-16 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maka', '0021_alter_userinteraction_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='coordinates',
            field=models.TextField(default='Coord'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField()),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='maka.user')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='maka.user')),
            ],
        ),
    ]
