# Generated by Django 5.0.3 on 2024-04-10 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maka', '0022_venue_coordinates_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maka.address'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='coordinates',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='point_of_contact',
            field=models.ManyToManyField(blank=True, to='maka.keyperson'),
        ),
    ]
