# Generated by Django 5.0.3 on 2024-04-10 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maka', '0023_alter_venue_address_alter_venue_coordinates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='point_of_contact',
            new_name='key_persons',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='owner',
        ),
    ]
