# Generated by Django 5.0.3 on 2024-04-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maka', '0025_alter_keyperson_email_alter_keyperson_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyperson',
            name='venue_independent',
            field=models.BooleanField(default=False),
        ),
    ]
