# Generated by Django 5.0.3 on 2024-04-11 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maka', '0026_keyperson_venue_independent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='type',
            new_name='event_type',
        ),
    ]
