# Generated by Django 5.0.3 on 2024-04-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maka', '0027_rename_type_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventuser',
            name='role',
            field=models.CharField(choices=[('HT', 'Host'), ('CR', 'Creator'), ('CT', 'CoHost')], default='HT', max_length=2),
        ),
    ]
