# Generated by Django 5.0.3 on 2024-04-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maka', '0028_alter_eventuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventuser',
            name='role',
            field=models.CharField(choices=[('HT', 'Host'), ('CR', 'Creator'), ('CT', 'CoHost'), ('SF', 'Staff'), ('SY', 'Security'), ('AN', 'Admin')], default='HT', max_length=2),
        ),
    ]
