# Generated by Django 5.0.3 on 2024-04-11 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maka', '0030_alter_eventdate_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdate',
            name='event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='maka.event'),
        ),
    ]
