# Generated by Django 5.0.3 on 2024-04-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maka', '0031_alter_eventdate_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='lead_status',
            field=models.CharField(choices=[('PT', 'Prospect'), ('CT', 'Client')], default='PT', max_length=2),
        ),
    ]
