# Generated by Django 5.0.3 on 2024-04-12 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maka', '0032_venue_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcheckin',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventcheckins', to='maka.event'),
        ),
    ]
