# Generated by Django 5.0.3 on 2024-04-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maka', '0033_alter_eventcheckin_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='current_interaction',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
