# Generated by Django 5.0.3 on 2024-04-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maka', '0034_userinteraction_current_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='seen',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
